### ISSUE TITLE
make_pair이 안되는 이유

### ISSUE THREAD

**Issue by Elenesgu** [nays850/scaling-octo-tribble#1]
```
T1 a;
T2 b;

make_pair<T1, T2>(a, b);
```

위 문은 컴파일 에러의 원인이 된다. 이유는 무엇일까?

**Comment by nays850** [comment]
컴파일할 때 템플릿 함수 내의 T1, T2를 함수가 불릴 때 사용되는 실제 타입들로 변환하는거랑 관련이 있을지도

**Comment by Elenesgu** [comment]
http://en.cppreference.com/w/cpp/utility/pair/make_pair
make_pair 원형을 보면 안될것 같기는 하다.
그러나 make_pair<decay<T1>::type, decay<T2>::type>(a, b)도 안댐
